// Parsers for untrusted client input. Every Socket.IO payload goes through
// one of these before it reaches the game room; anything unexpected yields
// null and is answered with 'invalid-payload'.
import {
  PROMOTION_PIECES,
  parseSquare,
  type PromotionPiece,
  type Square,
} from '../shared/chess/index.ts';
import {
  MAX_CHAT_LENGTH,
  MAX_NAME_LENGTH,
  MAX_ROOM_NAME_LENGTH,
  type MascotTug,
} from '../shared/protocol.ts';

export interface ParsedMove {
  readonly from: Square;
  readonly to: Square;
  readonly promotion: PromotionPiece | null;
  readonly ply: number;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

export function parseMoveRequest(value: unknown): ParsedMove | null {
  if (!isRecord(value)) return null;
  const { from, to, promotion, ply } = value;
  if (typeof from !== 'string' || typeof to !== 'string') return null;
  const fromSquare = parseSquare(from);
  const toSquare = parseSquare(to);
  if (fromSquare === null || toSquare === null) return null;
  if (typeof ply !== 'number' || !Number.isInteger(ply) || ply < 0) return null;
  let piece: PromotionPiece | null = null;
  if (promotion !== undefined && promotion !== null) {
    piece = PROMOTION_PIECES.find((candidate) => candidate === promotion) ?? null;
    if (piece === null) return null;
  }
  return { from: fromSquare, to: toSquare, promotion: piece, ply };
}

/**
 * Removes control and invisible formatting characters (e.g. bidi overrides,
 * zero-width spaces) and collapses whitespace. Rendering always uses
 * textContent, so this is about readability and impersonation, not XSS.
 */
function cleanText(value: string): string {
  return value
    .normalize('NFC')
    .replace(/[\p{Cc}\p{Cf}\p{Zl}\p{Zp}]/gu, ' ')
    .replace(/\s+/gu, ' ')
    .trim();
}

function parseBoundedText(value: unknown, maxLength: number): string | null {
  if (typeof value !== 'string' || value.length > maxLength * 4) return null;
  const text = cleanText(value);
  const length = text.match(/./gsu)?.length ?? 0; // code points, not UTF-16 units
  return length >= 1 && length <= maxLength ? text : null;
}

export const parseName = (value: unknown): string | null =>
  parseBoundedText(value, MAX_NAME_LENGTH);

export const parseChatText = (value: unknown): string | null =>
  parseBoundedText(value, MAX_CHAT_LENGTH);

/** Room names are optional: an empty name means "use the default". */
export function parseRoomName(value: unknown): string | null | undefined {
  if (value === undefined || value === null) return null;
  if (typeof value === 'string' && value.trim() === '') return null;
  return parseBoundedText(value, MAX_ROOM_NAME_LENGTH) ?? undefined;
}

/** Room ids are generated by the server (URL-safe base64). */
export function parseRoomId(value: unknown): string | null {
  return typeof value === 'string' && /^[A-Za-z0-9_-]{4,32}$/.test(value) ? value : null;
}

/** Session tokens are random, URL-safe strings generated by the client or server. */
export function parseToken(value: unknown): string | null {
  return typeof value === 'string' && /^[A-Za-z0-9_-]{16,64}$/.test(value) ? value : null;
}

function parseVector(value: unknown, limit: number): [number, number, number] | null {
  if (!Array.isArray(value) || value.length !== 3) return null;
  const numbers = value.filter(
    (n): n is number => typeof n === 'number' && Number.isFinite(n) && Math.abs(n) <= limit,
  );
  if (numbers.length !== 3) return null;
  const [x = 0, y = 0, z = 0] = numbers.map((n) => Math.round(n * 1000) / 1000);
  return [x, y, z];
}

/** A pull of a player's 몽돌이: a point on the pebble and an offset, both small. */
export function parseMascotTug(value: unknown): MascotTug | null {
  if (!isRecord(value) || typeof value.release !== 'boolean') return null;
  const grab = parseVector(value.grab, 1);
  const pull = parseVector(value.pull, 3);
  return grab && pull ? { grab, pull, release: value.release } : null;
}

/** Socket.IO acknowledgement callbacks arrive as the last argument, if at all. */
export function isAck(value: unknown): value is (...args: unknown[]) => void {
  return typeof value === 'function';
}
